import { defineConfig } from 'vite';
import fs from 'fs';
import path from 'path';
import { VitePWA } from 'vite-plugin-pwa';

const isLocal = process.env.NODE_ENV !== 'production' && process.env.CI !== 'true';

export default defineConfig({
  server: {
    host: 'facets.local',
    port: 5173,
    ...(isLocal && {
      https: {
        key: fs.readFileSync('/etc/apache2/ssl/tmp.local+12-key.pem'),
        cert: fs.readFileSync('/etc/apache2/ssl/tmp.local+12.pem'),
      },
    }),
    open: true,
  },
  build: {
    rollupOptions: {
      input: {
        'game/index': path.resolve(__dirname, 'game/index.html'),
        'game/stats': path.resolve(__dirname, 'game/stats.html'),
        main: path.resolve(__dirname, 'index.html'),
        generate: path.resolve(__dirname, 'generate.html'),
      },
    },
    // minify: false,
  },
  plugins: [
    VitePWA({
      includeAssets: [
        'favicon-alt.png',
        'favicon.svg',
        'fonts/Abel-Regular.ttf',
        'fonts/Bungee-Regular.ttf',
        'fonts/NovaFlat-Regular.ttf',
        'helpers/console-enhancer.js',
        'helpers/console-enhancer.min.js',
        'styles/checkbox.css',
        'styles/checkbox.min.css',
        'styles/flower.css',
        'styles/focus.css',
        'styles/focus.min.css',
        'styles/light.css',
        'styles/light.min.css',
        'styles/main.css',
        'styles/main.min.css',
        'styles/normalize.css',
        'styles/normalize.min.css',
        'styles/simple-min.css',
        'styles/simple.css',
        'styles/simple.min.css',
        'images/favicon.png',
        'images/1.png',
        'images/2.png',
        'images/3.png',
        'images/4.png',
        'images/5.png',
        'images/6.png',
        'images/7.png',
        'images/diamond-back.svg',
        'images/diamond-light.svg',
        'images/diamond.svg',
        'images/facets_og.png',
        'images/icon-alert.svg',
        'images/icon-anon.svg',
        'images/icon-bmc.svg',
        'images/icon-calendar-1.svg',
        'images/icon-calendar-2.svg',
        'images/icon-calendar-3.svg',
        'images/icon-calendar-4.svg',
        'images/icon-calendar-5.svg',
        'images/icon-calendar-6.svg',
        'images/icon-calendar-7.svg',
        'images/icon-calendar-8.svg',
        'images/icon-calendar-9.svg',
        'images/icon-calendar-10.svg',
        'images/icon-calendar-11.svg',
        'images/icon-calendar-12.svg',
        'images/icon-calendar.svg',
        'images/icon-check.svg',
        'images/icon-chevron-left.svg',
        'images/icon-chevron-right.svg',
        'images/icon-continue.svg',
        'images/icon-contract.svg',
        'images/icon-credits.svg',
        'images/icon-daily.svg',
        'images/icon-download.svg',
        'images/icon-edit.svg',
        'images/icon-expand.svg',
        'images/icon-eye.svg',
        'images/icon-feedback.svg',
        'images/icon-globe.svg',
        'images/icon-gradcap.svg',
        'images/icon-info.svg',
        'images/icon-like.svg',
        'images/icon-meeples.svg',
        'images/icon-play.svg',
        'images/icon-question.svg',
        'images/icon-quit.svg',
        'images/icon-rotatearrow.svg',
        'images/icon-settings.svg',
        'images/icon-share.svg',
        'images/icon-spinner.svg',
        'images/icon-x.svg',
        'images/icon96.png',
        'images/icon120.png',
        'images/icon180.png',
        'images/icon192.png',
        'images/icon512-apple-touch.png',
        'images/icon512-maskable.png',
        'images/icon512.png',
        'images/icon1024-apple-touch.png',
        'images/logo-discord.svg',
        'images/logo-facets.svg',
        'images/pan-1.svg',
        'images/pan-2.svg',
        'images/pan-3.svg',
        'images/pan-4.svg',
        'images/pan-5.svg',
        'images/pan-6.svg',
        'images/pan-7.svg',
        'images/pan-8.svg',
        'images/rotator-icon.svg',
        'images/tut-4-light.svg',
        'images/tut-4.svg',
        'images/tut-6-light.svg',
        'images/tut-6.svg',
        'images/tut-7-light.svg',
        'images/tut-7.svg',
        'images/Union.svg',
        'images/wallpapers/civilization.webp',
        'images/wallpapers/common.webp',
        'images/wallpapers/emoji.webp',
        'images/wallpapers/entertainment.webp',
        'images/wallpapers/nouns.webp',
        'images/wallpapers/prehistory.webp',
        'images/wallpapers/science.webp',
        'images/wallpapers/seasons.webp',
        'images/wallpapers/sports.webp',
        'images/wallpapers/verbs.webp',
      ],
      workbox: {
        navigateFallback: '/index.html',
        navigateFallbackDenylist: [
          /^\/game\//, // Don't fallback to /index.html for /game/ routes
          // Add other denylist patterns as needed
        ],
      },
    }),
  ],
});
