name: Deploy to GitHub Pages

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        id: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true

      - name: Notify Discord
        if: steps.deploy.outcome == 'success'
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          TAG_DESC=$(git for-each-ref refs/tags/${TAG_NAME} --format='%(contents)')
          # Remove the tag name from the description if it exists
          TAG_DESC_CLEANED=$(echo "$TAG_DESC" | sed "s/${TAG_NAME}[[:space:]]*//")
          CONTENT="Tag pushed: **${TAG_NAME}** ${TAG_DESC_CLEANED}"
          PAYLOAD=$(jq -n --arg content "$CONTENT" '{content: $content}')
          curl -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
