name: Notify Discord on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag info
        id: tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          TAG_DESC=$(git for-each-ref refs/tags/${GITHUB_REF#refs/tags/} --format='%(contents)')
          echo "TAG_DESC=$TAG_DESC" >> $GITHUB_ENV

      - name: Send to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"🏷️ New tag pushed: **${TAG_NAME}**\n📝 Description: ${TAG_DESC}\"}" \
          https://discord.com/api/webhooks/1408494736255356960/_LXtxWR1G6A-uwDq1VPWuWDI7CHUyqrkTt_jRrDCD8iBjhuXqM4Rx_A575iEiA0uBCoU
