name: Open URL at Midnight

on:
  schedule:
    - cron: '0 0 * * *' # Midnight GMT (4:00 PM PST)
    - cron: '29 4 * * *' # 4:29 AM GMT (8:29 PM PST)
  workflow_dispatch: # Allows manual triggering

jobs:
  open-url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/puppeteer.js') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Updated Node version to 18

      - name: Install Puppeteer
        run: npm install puppeteer@24.0.0 # Ensures Puppeteer version aligns with required Node version

      - name: Execute Puppeteer script
        run: node puppeteer.js

      - name: Log GitHub Action Status
        run: echo "GitHub Action completed successfully" # Custom log message
