name: Open URL at Midnight

on:
  schedule:
    - cron: '0 0 * * *' # This cron expression represents midnight GMT (0 0 * * *)
    - cron: '0 4 * * *' # 4 AM GMT (0 4 * * *)

jobs:
  open-url:
    runs-on: ubuntu-latest
    steps:
      - name: Open URL
        uses: wei/curl@master # Use an existing action to open URLs
        with:
          url: 'https://facets.bigtentgames.com/generate.html?generated=true'
      - name: Wait for 2 minutes
        run: sleep 120
      - name: Reload URL
        run: curl 'https://facets.bigtentgames.com/generate.html?generated=true'
      - name: Wait for 30 seconds
        run: sleep 30
