name: Open URL at Midnight

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 5 * * *'

jobs:
  open-url:
    runs-on: ubuntu-latest
    steps:
      - name: Open URL and capture cookies
        run: curl -c cookies.txt 'https://facets.bigtentgames.com/generate.html?generated=true'
      - name: Wait for 2 minutes
        run: sleep 120
      - name: Reload URL with cookies
        run: curl -b cookies.txt 'https://facets.bigtentgames.com/generate.html?generated=true'
      - name: Wait for 30 seconds
        run: sleep 30
