class WordObject {
  constructor(spec) {
    this.id = spec.id === undefined ? -1 : spec.id;
    this.value = spec.value === undefined ? '' : spec.value;
  }
}

getUniqueWords = function (_words, _num = 20, _exclude = null) {
  if (_exclude !== null) {
    _words = _words.filter((word) => !_exclude.includes(word.value));
  }

  let shuffledWords = [..._words];
  for (let i = shuffledWords.length - 1; i > 0; i--) {
    let j = Math.floor(Math.random() * (i + 1));
    [shuffledWords[i], shuffledWords[j]] = [shuffledWords[j], shuffledWords[i]];
  }

  return shuffledWords.slice(0, _num);
};

getWordIndex = function (_word) {
  return Nouns.concat(Verbs).findIndex((value) => value === _word);
};

getJustWords = function (_array) {
  let wordArray = [];
  _array.forEach((w) => {
    wordArray.push(w.value);
  });

  //wordArray = wordArray.join(', ');

  return wordArray;
};

createWordArray = function (_array, _index = 0) {
  let index = _index;
  let newArray = '';
  _array.forEach((word) => {
    newArray += '{"id":' + index++ + ',"value":"' + word + '"},';
  });
  return newArray;
};

sortWords = function (_array) {
  _array.sort((a, b) => {
    if (a < b) {
      return -1;
    }
    if (a > b) {
      return 1;
    }
    return 0;
  });

  return _array;
};

findDuplicateWords = function (_array) {
  let duplicates = _array.filter((item, index) => {
    let _item = JSON.stringify(item);
    return _array.map((e) => JSON.stringify(e)).indexOf(_item) != index && _array.map((e) => JSON.stringify(e)).lastIndexOf(_item) == index;
  });

  return duplicates;
};

let prehistoryWords = [
  'acceleration',
  'action',
  'adaptation',
  'adventure',
  'aeon',
  'agate',
  'alchemy',
  'algae',
  'algorithm',
  'amber',
  'amphibian',
  'amulet',
  'analysis',
  'ancient',
  'animal',
  'animation',
  'archaeozoic',
  'archean',
  'architecture',
  'art',
  'artifact',
  'astrology',
  'astronomy',
  'atom',
  'autumn',
  'bacteria',
  'balance',
  'bead',
  'beauty',
  'biology',
  'biosphere',
  'bird',
  'birth',
  'blessing',
  'bone',
  'brain',
  'bronze',
  'cambrian',
  'carboniferous',
  'castle',
  'caveman',
  'cell',
  'cenozoic',
  'ceramic',
  'ceremony',
  'change',
  'charm',
  'chemistry',
  'cinema',
  'city',
  'climate',
  'coin',
  'cold',
  'color',
  'comedy',
  'comics',
  'community',
  'compound',
  'computer',
  'consciousness',
  'continent',
  'contraction',
  'coral',
  'costume',
  'crab',
  'cretaceous',
  'crystal',
  'culture',
  'cuneiform',
  'curse',
  'cycle',
  'dance',
  'data',
  'death',
  'decoration',
  'deity',
  'density',
  'desert',
  'design',
  'development',
  'devonian',
  'diamond',
  'dig',
  'dimension',
  'divination',
  'divine',
  'dna',
  'drama',
  'dream',
  'ecology',
  'ecosystem',
  'education',
  'electricity',
  'elegance',
  'element',
  'emerald',
  'emotion',
  'energy',
  'enzyme',
  'eocene',
  'eon',
  'epoch',
  'era',
  'esoteric',
  'evolution',
  'excavate',
  'existence',
  'expansion',
  'experiment',
  'extinction',
  'fact',
  'fantasy',
  'farm',
  'fashion',
  'fauna',
  'feeling',
  'fiction',
  'field',
  'fish',
  'flint',
  'flora',
  'folklore',
  'force',
  'forecast',
  'forest',
  'formation',
  'fort',
  'fossil',
  'fungus',
  'galaxy',
  'garnet',
  'gas',
  'gem',
  'gene',
  'geology',
  'glyph',
  'god',
  'goddess',
  'grace',
  'gravity',
  'growth',
  'hadean',
  'hardware',
  'harmony',
  'healing',
  'hearing',
  'heat',
  'hieroglyph',
  'hill',
  'history',
  'holocene',
  'holy',
  'hormone',
  'horror',
  'hypothesis',
  'icon',
  'idol',
  'image',
  'information',
  'inheritance',
  'inscription',
  'insect',
  'intelligence',
  'internet',
  'interpretation',
  'iron',
  'island',
  'jade',
  'jewelry',
  'jungle',
  'jurassic',
  'knowledge',
  'lake',
  'layer',
  'learning',
  'legend',
  'life',
  'light',
  'liquid',
  'literature',
  'magic',
  'magical',
  'magnetism',
  'mammal',
  'mammoth',
  'mantra',
  'manuscript',
  'mask',
  'mass',
  'mathematics',
  'measurement',
  'meditation',
  'mega',
  'memory',
  'mesozoic',
  'meteorology',
  'mind',
  'mineral',
  'miocene',
  'miracle',
  'molecule',
  'motion',
  'mountain',
  'mutation',
  'mystery',
  'mystical',
  'mysticism',
  'mythology',
  'nature',
  'neanderthal',
  'neogene',
  'obelisk',
  'observation',
  'occult',
  'ocean',
  'offering',
  'oligocene',
  'omen',
  'onyx',
  'opal',
  'oracle',
  'ordovician',
  'ornament',
  'painting',
  'palace',
  'paleo',
  'paleocene',
  'paleogene',
  'paleozoic',
  'papyrus',
  'paranormal',
  'pattern',
  'pearl',
  'peninsula',
  'perception',
  'period',
  'permian',
  'phanerozoic',
  'philosophy',
  'physics',
  'planet',
  'plant',
  'plasma',
  'pleistocene',
  'pliocene',
  'poem',
  'population',
  'pottery',
  'prayer',
  'precambrian',
  'prediction',
  'pressure',
  'program',
  'progress',
  'prophecy',
  'protein',
  'proterozoic',
  'psychology',
  'pyramid',
  'quartz',
  'quaternary',
  'radio',
  'reality',
  'region',
  'relic',
  'religion',
  'reproduction',
  'reptile',
  'research',
  'revolution',
  'ritual',
  'river',
  'rna',
  'rock',
  'romance',
  'ruby',
  'ruin',
  'saber',
  'sacred',
  'sacrifice',
  'sapphire',
  'school',
  'science',
  'scroll',
  'sculpture',
  'sea',
  'season',
  'sediment',
  'selection',
  'sense',
  'shape',
  'shell',
  'shellfish',
  'sight',
  'sign',
  'silurian',
  'site',
  'size',
  'smell',
  'sociology',
  'software',
  'solid',
  'song',
  'sorcery',
  'soul',
  'sound',
  'space',
  'speciation',
  'speed',
  'spell',
  'spider',
  'spirit',
  'spring',
  'star',
  'statue',
  'stele',
  'stone',
  'story',
  'stratum',
  'style',
  'summer',
  'supernatural',
  'symbol',
  'tablet',
  'tale',
  'talisman',
  'tantra',
  'taste',
  'teaching',
  'technology',
  'television',
  'temple',
  'tertiary',
  'texture',
  'theory',
  'thought',
  'thriller',
  'time',
  'topaz',
  'totem',
  'touch',
  'town',
  'tragedy',
  'trend',
  'triassic',
  'trilobite',
  'turquoise',
  'understanding',
  'universe',
  'university',
  'valley',
  'variation',
  'velocity',
  'village',
  'virus',
  'vision',
  'vitamin',
  'volume',
  'weather',
  'weight',
  'winter',
  'wisdom',
  'witchcraft',
  'yoga',
  'artifact',
  'dinosaur',
];
